export const movies = [
  {
    id: 1,
    title: 'Avengers Endgame',
    releaseYear: 2021,
    genre: 'Action',
    rating: 8.5,
    description: 'Description of Movie 1',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
    director: 'Joe Russo',
    posterUrl: 'https://example.com/poster1.jpg',
  },
  {
    id: 2,
    title: 'The Dark Knight',
    releaseYear: 2008,
    genre: 'Action',
    rating: 9,
    description: 'Description of Movie 2',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan',
    posterUrl: 'https://example.com/poster2.jpg',
  },
  {
    id: 3,
    title: 'Inception',
    releaseYear: 2010,
    genre: 'Action',
    rating: 8.8,
    description: 'Description of Movie 3',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    director: 'Christopher Nolan',
    posterUrl: 'https://example.com/poster3.jpg',
  },
  {
    id: 4,
    title: 'The Matrix',
    releaseYear: 1999,
    genre: 'Action',
    rating: 8.7,
    description: 'Description of Movie 4',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    director: 'Lana Wachowski',
    posterUrl: 'https://example.com/poster4.jpg',
  },
  {
    id: 5,
    title: 'Interstellar',
    releaseYear: 2014,
    genre: 'Adventure',
    rating: 8.6,
    description: 'Description of Movie 5',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    posterUrl: 'https://example.com/poster5.jpg',
  },
  {
    id: 6,
    title: 'The Avengers',
    releaseYear: 2012,
    genre: 'Action',
    rating: 8.1,
    description: 'Description of Movie 6',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
    director: 'Joss Whedon',
    posterUrl: 'https://example.com/poster6.jpg',
  },
  {
    id: 7,
    title: 'Star Wars: The Force Awakens',
    releaseYear: 2015,
    genre: 'Action',
    rating: 8.3,
    description: 'Description of Movie 7',
    actors: ['Daisy Ridley', 'John Boyega', 'Oscar Isaac'],
    director: 'J.J. Abrams',
    posterUrl: 'https://example.com/poster7.jpg',
  }
]