import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased p-6 m-0`}
      >
        {/* Wrapping children in a max-width container is often helpful */}
        <main className="w-full max-w-2xl">
          {children}
        </main>
      </body>
    </html>
  );
}
